import sys
with open('alembic/versions/5032740e5b4c_phase_3_embeddings.py', 'r', encoding='utf-8') as f:
    c = f.read()

c = c.replace(
    'import sqlalchemy as sa',
    '''import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

try:
    from pgvector.sqlalchemy import Vector
    HAS_PGVECTOR = True
except ImportError:
    HAS_PGVECTOR = False'''
)

c = c.replace(
    '''def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###''',
    '''def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    if conn.engine.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    embedding_type = Vector() if HAS_PGVECTOR and conn.engine.name == "postgresql" else sa.JSON()
    # ### commands auto generated by Alembic - please adjust! ###'''
)

c = c.replace(
    "sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True),",
    "sa.Column('embedding', embedding_type, nullable=True),"
)

with open('alembic/versions/5032740e5b4c_phase_3_embeddings.py', 'w', encoding='utf-8') as f:
    f.write(c)
