"""phase 3 embeddings

Revision ID: 5032740e5b4c
Revises: c2b49b035a68
Create Date: 2026-10-03 13:13:18.436280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

try:
    from pgvector.sqlalchemy import Vector
    HAS_PGVECTOR = True
except ImportError:
    HAS_PGVECTOR = False


# revision identifiers, used by Alembic.
revision: str = '5032740e5b4c'
down_revision: Union[str, Sequence[str], None] = 'c2b49b035a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    if conn.engine.name == "postgresql":
        if not HAS_PGVECTOR:
            raise RuntimeError(
                "pgvector is required for PostgreSQL in Phase 3 embeddings. "
                "Install it using `pip install pgvector`."
            )
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        embedding_type = Vector()
    else:
        embedding_type = sa.JSON()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_metadata',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', embedding_type, nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id', 'model_name', 'model_version', 'content_hash', name='uix_embedding_idempotency')
    )
    # ### end Alembic commands ###

    # Production HNSW partial indexes for supported dimensions
    if conn.engine.name == "postgresql":
        for dim in [64, 384, 768]:
            op.execute(sa.text(f"""
                CREATE INDEX IF NOT EXISTS idx_embedding_hnsw_{dim}
                ON embedding_metadata
                USING hnsw ((embedding::vector({dim})) vector_cosine_ops)
                WHERE embedding_dimension = {dim}
            """))


def downgrade() -> None:
    """Downgrade schema."""
    conn = op.get_bind()
    if conn.engine.name == "postgresql" and HAS_PGVECTOR:
        for dim in [64, 384, 768]:
            op.execute(sa.text(f"DROP INDEX IF EXISTS idx_embedding_hnsw_{dim}"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embedding_metadata')
    # ### end Alembic commands ###

